const nfts = [
  {
    tokenId: 1,
    major: '6B041-В046 Economics',
    graduationDate: '30.06.2023',
    fullName: 'Осипов Анатолий Максимович',
    degree: 'Bachelor',
    GPA: '2.65',
    LatinHonors: '-',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '1',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/1.png',
  },
  {
    tokenId: 2,
    major: '6B061-В057 Computer and Information Sciences',
    graduationDate: '30.06.2023',
    fullName: 'Абатов Еркебулан Амангельдиевич',
    degree: 'Bachelor',
    GPA: '3.4',
    LatinHonors: 'Magna Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '2',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/2.png',
  },
  {
    tokenId: 3,
    major: '6B061-В057 Computer and Information Sciences',
    graduationDate: '30.06.2023',
    fullName: 'Абдугалина Анар Ризабековна',
    degree: 'Master',
    GPA: '3.3',
    LatinHonors: 'Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '3',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/3.png',
  },
  {
    tokenId: 4,
    major: '6B061-В057 Computer and Information Sciences',
    graduationDate: '30.06.2023',
    fullName: 'Байгалым Нуржан',
    degree: 'Bachelor',
    GPA: '3.4',
    LatinHonors: 'Summa Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '4',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/4.png',
  },
  {
    tokenId: 5,
    major: '6B061-В057 Computer and Information Sciences',
    graduationDate: '30.06.2023',
    fullName: 'Вагнер Владимир Егорович',
    degree: 'Bachelor',
    GPA: '3.24',
    LatinHonors: 'Magna Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '5',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/5.png',
  },
  {
    tokenId: 6,
    major: '6B041-В044 Business Administration',
    graduationDate: '24.06.2023',
    fullName: 'Кабдешев Рашид Галламович',
    degree: 'Bachelor',
    GPA: '2.75',
    LatinHonors: '-',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '6',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/6.png',
  },
  {
    tokenId: 7,
    major: '6B041-В044 Business Administration',
    graduationDate: '24.06.2023',
    fullName: 'Жакеев Улан Максатович',
    degree: 'Bachelor',
    GPA: '3.03',
    LatinHonors: 'Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '7',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/7.png',
  },
  {
    tokenId: 8,
    major: '6B071-В062 General Engineering',
    graduationDate: '24.06.2023',
    fullName: 'Касенова Айжан Жуматаевна',
    degree: 'Bachelor',
    GPA: '2.98',
    LatinHonors: 'Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '8',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/8.png',
  },
  {
    tokenId: 9,
    major: '6B041-В046 Economics',
    graduationDate: '24.06.2023',
    fullName: 'Пак Алексей Андреевич',
    degree: 'Bachelor',
    GPA: '3.7',
    LatinHonors: 'Summa Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '9',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/9.png',
  },
  {
    tokenId: 10,
    major: '6B041-В046 Economics',
    graduationDate: '24.06.2023',
    fullName: 'Шабаева Алиса Вадимовна',
    degree: 'Bachelor',
    GPA: '3.3',
    LatinHonors: 'Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '10',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/10.png',
  },
  {
    tokenId: 11,
    major: '6B041-В046 Economics',
    graduationDate: '30.06.2023',
    fullName: 'Медведев Игорь Иванович',
    degree: 'Bachelor',
    GPA: '2.79',
    LatinHonors: '-',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '11',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/11.png',
  },
  {
    tokenId: 12,
    major: '6B061-В057 Computer and Information Sciences',
    graduationDate: '30.06.2023',
    fullName: 'Поляков Марк Евгеньевич',
    degree: 'Bachelor',
    GPA: '3.32',
    LatinHonors: 'Magna Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '12',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/12.png',
  },
  {
    tokenId: 13,
    major: '6B061-В057 Computer and Information Sciences',
    graduationDate: '30.06.2023',
    fullName: 'Назаров Гордей Даниилович',
    degree: 'Master',
    GPA: '3.24',
    LatinHonors: 'Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '13',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/13.png',
  },
  {
    tokenId: 14,
    major: '6B061-В057 Computer and Information Sciences',
    graduationDate: '30.06.2023',
    fullName: 'Андреева Вера Максимовна',
    degree: 'Bachelor',
    GPA: '3.43',  
    LatinHonors: 'Summa Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '14',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/14.png',
  },
  {
    tokenId: 15,
    major: '6B061-В057 Computer and Information Sciences',
    graduationDate: '30.06.2023',
    fullName: 'Жданов Фёдор Михайлович',
    degree: 'Bachelor',
    GPA: '3.31',
    LatinHonors: 'Magna Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '15',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/15.png',
  },
  {
    tokenId: 16,
    major: '6B041-В044 Business Administration',
    graduationDate: '24.06.2023',
    fullName: 'Иванов Тимур Станиславович',
    degree: 'Bachelor',
    GPA: '2.62',
    LatinHonors: '-',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '16',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/16.png',
  },
  {
    tokenId: 17,
    major: '6B041-В044 Business Administration',
    graduationDate: '24.06.2023',
    fullName: 'Прохоров Сергей Алиевич',
    degree: 'Bachelor',
    GPA: '3.12',
    LatinHonors: 'Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '17',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/17.png',
  },
  {
    tokenId: 18,
    major: '6B071-В062 General Engineering',
    graduationDate: '24.06.2023',
    fullName: 'Филиппов Роман Михайлович',
    degree: 'Bachelor',
    GPA: '3.02',
    LatinHonors: 'Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '18',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/18.png',
  },
  {
    tokenId: 19,
    major: '6B041-В046 Economics',
    graduationDate: '24.06.2023',
    fullName: 'Казакова Алиса Макаровна',
    degree: 'Bachelor',
    GPA: '3.72',
    LatinHonors: 'Summa Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '19',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/19.png',
  },
  {
    tokenId: 20,
    major: '6B041-В046 Economics',
    graduationDate: '24.06.2023',
    fullName: 'Булгаков Иван Игоревич',
    degree: 'Bachelor',
    GPA: '3.34',
    LatinHonors: 'Cum Laude',
    admissionDate: 'НАРХОЗ 2020',
    commencementDate: 'НАРХОЗ 2023',
    diplomaId: '20',
    image: 'https://gateway.pinata.cloud/ipfs/QmZr39z7sEmoBc28Zdg6tznbiBxJTGgnJP6M4kqZvbFBXA/20.png',
  },
];

export default nfts;
