const nfts = [
    {
      tokenId: 1,
      major: 'Computer Science',
      graduationDate: 'May 2022',
      fullName: 'John William Doe',
      diplomaId: 'ABC12345',
      image: 'https://via.placeholder.com/150x150.png?text=Sample+Diploma+Image',
    },
    {
      tokenId: 2,
      major: 'Graphic Design',
      graduationDate: 'December 2021',
      fullName: 'Jane Elizabeth Smith',
      diplomaId: 'DEF67890',
      image: 'https://via.placeholder.com/150x150.png?text=Sample+Diploma+Image',
    },
    {
      tokenId: 3,
      name: 'Bob Johnson',
      major: 'Business Administration',
      graduationDate: 'August 2022',
      fullName: 'Robert Johnson',
      diplomaId: 'GHI24680',
      image: 'https://via.placeholder.com/150x150.png?text=Sample+Diploma+Image',
    },
    {
      tokenId: 4,
      major: 'Marketing',
      graduationDate: 'June 2021',
      fullName: 'Emily Davis',
      diplomaId: 'JKL54321',
      image: 'https://via.placeholder.com/150x150.png?text=Sample+Diploma+Image',
    },
    {
      tokenId: 5,
      major: 'Education',
      graduationDate: 'March 2023',
      fullName: 'Michael Johnson',
      diplomaId: 'MNO13579',
      image: 'https://via.placeholder.com/150x150.png?text=Sample+Diploma+Image',
    },
    {
      tokenId: 6,
      major: 'Psychology',
      graduationDate: 'November 2022',
      fullName: 'Rachel Lee',
      diplomaId: 'PQR24680',
      image: 'https://via.placeholder.com/150x150.png?text=Sample+Diploma+Image',
    },
    {
      tokenId: 7,
      major: 'Chemical Engineering',
      graduationDate: 'May 2023',
      fullName: 'David Wang',
      diplomaId: 'STU12345',
      image: 'https://via.placeholder.com/150x150.png?text=Sample+Diploma+Image',
    },
    {
      tokenId: 8,
      major: 'Environmental Science',
      graduationDate: 'December 2021',
      fullName: 'Sarah Patel',
      diplomaId: 'VWX67890',
      image: 'https://via.placeholder.com/150x150.png?text=Sample+Diploma+Image',
    },
    {
      tokenId: 9,
      major: 'Journalism',
      graduationDate: 'August 2022',
      fullName: 'Daniel Kim',
      diplomaId: 'YZA24680',
      image: 'https://via.placeholder.com/150x150.png?text=Sample+Diploma+Image',
    },
    {
      tokenId: 10,
      major: 'Biology',
      graduationDate: 'May 2021',
      fullName: 'Ashley Brown',
      diplomaId: 'BCD13579',
      image: 'https://via.placeholder.com/150x150.png?text=Sample+Diploma+Image',
    },
  ];
  
  export default nfts;
  